version: '2'

services:
  drupal: # https://hub.docker.com/_/drupal/
    build:
      context: . # it is equal to "build: ."
    image: custom-drupal
    ports:
      - '8888:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
      - drupal-data:/var/lib/postgresql/data
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpassword'
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
